---
- name: Install IIS Role on Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Install IIS Role
      win_feature:
        name: Web-Server
        state: present

    - name: Ensure IIS service is running
      win_service:
        name: W3SVC
        state: started
        start_mode: auto