---
- name: Install a Role on Windows Servers
  hosts: all
  gather_facts: false
  tasks:
    - name: Install IIS on Windows
      ansible.windows.win_feature:
        name: 
         - Web-Server
         - Web-Common-Http
        include_sub_features: true 
        include_management_tools: true
        state: present
      #register: win_feature
