- name: Install applications using Chocolatey
  hosts: all
  gather_facts: false

  tasks:

    - name: Install Firefox
      chocolatey.chocolatey.win_chocolatey:
        name: firefox
        state: present

    - name: Install 7-Zip
      chocolatey.chocolatey.win_chocolatey:
        name: 7zip
        state: present

    - name: Install Notepad++
      chocolatey.chocolatey.win_chocolatey:
        name: notepadplusplus
        state: present

