---
- name: Create and power on Windows VM from vCenter template
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: "172.16.1.111"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter: "Datacenter"
    template: "Win-2019"
    vm_name: "DC-Doral"
    vm_folder: "/"
    datastore: "HP800-DS1"
    network_name: "VM Network"
    vm_hardware:
      num_cpus: 2
      memory_mb: 4096

  tasks:
    - name: Clone VM from template and power on
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        folder: "{{ vm_folder }}"
        name: "{{ vm_name }}"
        template: "{{ template }}"
        state: poweredon
        datastore: "{{ datastore }}"
        networks:
          - name: "{{ network_name }}"
        hardware:
          memory_mb: "{{ vm_hardware.memory_mb }}"
          num_cpus: "{{ vm_hardware.num_cpus }}"
      delegate_to: localhost
