---
- name: Install Applications with Chocolatey
  hosts: all
  gather_facts: false

  vars:
    browsers:
      - googlechrome
      - firefox
      - microsoft-edge

    development_tools:
      - git
      - nodejs
      - putty
      - winscp

    productivity_tools:
      - 7zip
      - notepadplusplus
      - adobereader
      - vlc
      - teamviewer
      - zoom

  tasks:

    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Enable Chocolatey global confirmation (to avoid prompts)
      win_chocolatey_feature:
        name: allowGlobalConfirmation
        state: enabled

    - name: Install web browsers
      win_chocolatey:
        name: "{{ browsers }}"
        state: present
      tags: [browsers, web]

    - name: Install development tools
      win_chocolatey:
        name: "{{ development_tools }}"
        state: present
      tags: [development, dev-tools]

    - name: Install productivity applications
      win_chocolatey:
        name: "{{ productivity_tools }}"
        state: present
      tags: [productivity, office]

    - name: Install Google Chrome with specific parameters
      win_chocolatey:
        name: googlechrome
        state: present
        install_args: '/allusers'
      tags: browsers

    - name: Install Visual Studio Code with extensions
      win_chocolatey:
        name: vscode
        state: present
      tags: development

    - name: Remove unwanted applications
      win_chocolatey:
        name:
          - mcafee
          - norton
        state: absent
      tags: cleanup

    - name: Pin critical applications
      win_chocolatey:
        name:
          - googlechrome
          - firefox
        state: present
        pinned: yes
      tags: pin

    - name: Verify Chrome installation
      ansible.windows.win_stat:
        path: 'C:\Program Files\Google\Chrome\Application\chrome.exe'
      register: chrome_installed

    - name: Display Chrome installation status
      debug:
        msg: "Google Chrome is {{ 'installed' if chrome_installed.stat.exists else 'not installed' }}"

    - name: Verify VS Code installation
      ansible.windows.win_stat:
        path: 'C:\Program Files\Microsoft VS Code\Code.exe'
      register: vscode_installed

    - name: Display VS Code installation status
      debug:
        msg: "VS Code is {{ 'installed' if vscode_installed.stat.exists else 'not installed' }}"

    - name: Get list of installed Chocolatey packages
      win_chocolatey_facts:
      register: choco_packages

    - name: Display installed packages
      debug:
        msg: "Installed packages: {{ choco_packages.chocolatey | map(attribute='package') | list }}"
      tags: info
