---
- name: Provisioning System Software
  hosts: all

  vars_files:
    - app_list.yml

  tasks:
    - name: Install applications using Chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name }}"
        state: present
        force: yes
      loop: "{{ choco_packages }}"

