---
- name: Install Chocolatey and apps
  hosts: all
  gather_facts: false

  vars_files:
    - app_list.yml


  tasks:
    - name: Ensure Chocolatey is installed
      ansible.windows.win_chocolatey:
        state: present
    
    - name: Install applications using Chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name }}"
        state: present
        force: yes
      loop: "{{ choco_packages }}"

