---
- name: Install Docker on RHEL family (AlmaLinux, Rocky, RHEL)
  hosts: all
  become: true

  tasks:
    - name: Ensure required system packages are installed
      ansible.builtin.dnf:
        name:
          - dnf-utils
        state: present

    - name: Add Docker CE repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Add user 'rh' to docker group
      ansible.builtin.user:
        name: "rh"
        groups: docker
        append: yes
