---
- name: Install Docker on RHEL family (AlmaLinux, Rocky, RHEL)
  hosts: all
  become: true
  vars:
    docker_repo_url: "https://download.docker.com/linux/centos/docker-ce.repo"

  tasks:
    - name: Get OS major version
      set_fact:
        os_major_version: "{{ ansible_facts['distribution_major_version'] }}"

    - name: Adjust Docker repo URL for EL8/EL9
      set_fact:
        docker_repo_url: "https://download.docker.com/linux/centos/{{ os_major_version }}/x86_64/stable"

    - name: Install required packages
      ansible.builtin.dnf:
        name: dnf-utils
        state: present

    - name: Add Docker repository (EL8+ compatible)
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Stable for EL{{ os_major_version }}
        baseurl: "{{ docker_repo_url }}"
        enabled: true
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Add user 'rh' to docker group
      ansible.builtin.user:
        name: "rh"
        groups: docker
        append: yes
