---
- name: Update packages based on OS type
  hosts: all
  become: yes
  tasks:
    - name: Update on Debian-based
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update on RedHat-based
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
